### ISSUE TITLE
Extract Omise integration to a gem

### ISSUE THREAD

**Issue by fred** [omise/spree_demo#1]
The modifications on this demo repo should be extracted to a gem, so that we can add to any existing spree application.

for example, adding this to Gemfile should suffice: 

```
gem 'spree', github: 'spree/spree', branch: '3-0-stable'
gem 'spree_gateway', github: 'spree/spree_gateway', branch: '3-0-stable'
gem 'spree-omise', github: 'omise/spree-omise'
```

**Comment by robinclart** [comment]
Beware that `gem 'spree-omise'` will try to `require "spree/omise"` by default.

**Comment by zdk** [comment]
:+1:
